services:
  nginx-argocd:
    image: nginx:alpine
    container_name: nginx-argocd
    ports:
      - "80:80"
    volumes:
      - ./nginx-simple/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
